### ISSUE TITLE
`Terms` parameters APIs

### ISSUE THREAD

**Issue by kostysh** [windingtree/lpms-server#100]
`Terms` that are stored in the facility metadata (ServiceProviderData.terms) are just abstractions of reals `terms` that can be applied to the `bid`. `Terms parameters` is the term-specific data that is encoded using AbiEncoder.
We need to create a special API to assign a specific `term` to the concrete `space` with specific `term parameters`.

## API endpoint

```
POST /api/params/term/<facilityId>/<spaceId>/<termId>
Request body:
[ ['uint256'], [1209600] ]
```

## Implementaion

- accept POST with <facilityId> and <spaceId> and <termId> and request body
- encode request body using [AbiEncoder](https://docs.ethers.io/v5/api/utils/abi/coder/)
- save encoded data as parameters for the <termId> on <spaceId> in the <facilityId>

## This issue is blocked by

- https://github.com/windingtree/stays-models/issues/12
- #86
- #87 

## Tasks

- [ ] Implement POST API (adding parameters)
- [ ] Implement DELETE API (remove parameters)
- [ ] Implement tests for the new APIs
